### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by patriciachrysy** [patriciachrysy/ruby-enumerables-module#2]
SOme comments here please

**Comment by Kyle-Law** [comment]
Great Job @patriciachrysy ! The project is like 98% completed. Here are some few remarks:
- to check param other than Regex/Class, iterate over `self` and check if |i| == param (eg. 'cat' == 'cat' for TSE's example.)

**Comment by dili021** [comment]
Solution for the any/none/all:
![image](https://user-images.githubusercontent.com/55356496/75957463-5ae35f80-5eba-11ea-9ec3-dca18114cd32.png)
You were comparing item class with parameter and when you feed it a string literal it gives an error.
In the above screenshot I have changed it to item.match(param) and it's working

**Comment by patriciachrysy** [comment]
Thank you guys for your comments!
